---
name: Pull Request

on:
  pull_request:

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@v0.1.0-alpha.27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    name: ESLint
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["18"]

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          yarn install
          yarn lint

  audit:
    runs-on: ubuntu-latest
    name: Node Audit
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["18"]

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          yarn audit
        continue-on-error: true

  build:
    runs-on: ubuntu-latest
    name: Build IaC code
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["18"]

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          yarn install
          yarn build

  preview:
    runs-on: ubuntu-latest
    name: Pulumi Preview
    needs:
      - conform
      - lint
      - audit
      - build
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["18"]

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: hashicorp/vault-action@v3
        id: import-secrets
        with:
          method: jwt
          url: ${{ secrets.VAULT_ADDR }}
          path: ${{ secrets.VAULT_PATH }}
          role: ${{ secrets.VAULT_ROLE }}
          secrets: |
            github-homelab-buildkite-agents-home-infrastructure/data/pulumi access_token | PULUMI_ACCESS_TOKEN ;
            github-homelab-buildkite-agents-home-infrastructure/data/google-cloud region | CLOUDSDK_COMPUTE_REGION ;
            github-homelab-buildkite-agents-home-infrastructure/data/google-cloud workload_identity_provider | GOOGLE_WORKLOAD_IDENTITY_PROVIDER ;
            github-homelab-buildkite-agents-home-infrastructure/data/google-cloud ci_service_account | GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT ;
            github-homelab-buildkite-agents-home-infrastructure/data/github token | GH_PAT_TOKEN ;
            github-homelab-buildkite-agents-home-infrastructure/data/buildkite token | BUILDKITE_API_TOKEN ;
            github-homelab-buildkite-agents-home-infrastructure/data/tailscale oauth_client_id | TS_OAUTH_CLIENT_ID ;
            github-homelab-buildkite-agents-home-infrastructure/data/tailscale oauth_secret | TS_OAUTH_SECRET ;
            github-homelab-buildkite-agents-home-infrastructure/data/proxmox username | PROXMOX_VE_USERNAME ;
            github-homelab-buildkite-agents-home-infrastructure/data/proxmox password | PROXMOX_VE_PASSWORD ;
            github-homelab-buildkite-agents-home-infrastructure/data/proxmox endpoint | PROXMOX_VE_ENDPOINT ;
            github-homelab-buildkite-agents-home-infrastructure/data/proxmox insecure | PROXMOX_VE_INSECURE

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

      - run: |
          npm install -g yarn

      - run: |
          yarn install
          yarn build

      - uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ env.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ env.TS_OAUTH_SECRET }}
          tags: tag:github-actions
      
      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: prod
          comment-on-pr: true
          refresh: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        env:
          GITHUB_TOKEN: "${{ env.GH_PAT_TOKEN }}"
